# Defines the actions provided by the Minecraft Bedrock Server Manager integration.

send_command:
  description: Sends a command to the specified Minecraft server's console. Target entities or devices associated with the server instance you want to command.
  target:
  device:
    integration: bsm_home_assistant_integration
  fields:
    command:
      description: The command string to send to the server console (without the leading '/').
      required: true
      example: "say Hello World from Home Assistant!"
      selector:

prune_download_cache:
  description: Deletes older downloaded server archives from a specified directory on the manager host, keeping a defined number of newest files.
  fields:
    directory:
      description: The absolute path on the manager host where download files (.zip) are stored.
      required: true
      example: "/opt/minecraft_manager/.downloads/stable"
      selector:
        text: {}
    keep:
      description: "(Optional) Number of newest files to keep. Uses manager's default if omitted."
      required: false
      example: 3
      selector:
        number:
          min: 0
          step: 1
          mode: box